# Blue/red sentence examples for tests
BLUE_SENTENCES = [
    "Moonlight pooled across the glacier, casting a hushed glimmer over the crevasses.",
    "Morning mist hung above the harbor like a veil of cool glass.",
    "She wrapped herself in a scarf patterned with distant constellations.",
    "An Arctic fox trotted across frosted dunes beneath a pale dawn.",
    "The aquarium tunnel shimmered with tides full of glowing jellyfish.",
    "A steel bridge mirrored the river, sleek and quiet in winter air.",
    "Rows of hydrangeas leaned toward the gentle ocean breeze.",
    "An alpine lake sat still enough to reflect the snow-capped ridgeline.",
    "The scientist scribbled equations on slate-colored diagrams.",
    "Icebergs drifted past the research vessel like silent cathedrals.",
    "Her smartwatch gleamed with a metallic sheen under the fluorescent lights.",
    "Rain-soaked pavement glittered beneath the neon marquee.",
    "The drones buzzed above the stadium leaving ribbons of vapor.",
    "A kingfisher flashed past the reeds with a whisper of feathers.",
    "Fishermen hauled nets from the depths before sunrise.",
    "Starlight glimmered off the glass towers of the coastal city.",
    "A can of soda hissed as he pulled it from the chilled cooler.",
    "Snowmelt coursed through the gorge, quick and crystalline.",
    "Each icicle along the eaves chimed softly in the wind.",
    "Her eyes held the quiet calm of a mountain tarn.",
    "A squadron of jets painted contrails across the crisp morning.",
    "The commuter train hummed past fields drenched in early fog.",
    "He skimmed stones across the still surface of the quarry pond.",
    "Tiny forget-me-nots carpeted the shaded meadow.",
    "The architect chose glass panels that swallowed the sky.",
    "Whales surfaced beside the trawler with a spray of cold breath.",
    "A holographic display hovered above the console with clinical clarity.",
    "Skiers carved along powder that sparkled in the noon glare.",
    "The crystal bowl refracted sunlight onto the kitchen counter.",
    "Northern lights rippled over the silent tundra.",
    "A ceramic teacup cooled beside the open window.",
    "He unfolded a map speckled with distant island chains.",
    "The mountain bivouac rattled in the midnight squall.",
    "Seaglass littered the shoreline like smooth talismans.",
    "She adjusted the velvet curtains framing the rainy street.",
    "The library's skylight flooded the atrium with gentle luminescence.",
    "Distant thunder rolled over the calm expanse of the bay.",
    "A school of sardines whirled like liquid mercury.",
    "Cool vapor drifted from the cryogenic chamber.",
    "The snow husky shook droplets from its water bowl.",
    "Her notebook cover shimmered with iridescent foil.",
    "The lighthouse beacon swept across sleeping waves.",
    "Mussels clung to the tidal rocks with polished shells.",
    "A drone camera hovered above the ice floe expedition.",
    "He stirred a smoothie infused with coastal berries.",
    "The orchestra's glass armonica produced a chilling resonance.",
    "Polar research tents flapped under a sunless noon.",
    "She set gemstones into the circuit board like tiny stars.",
    "Rainclouds gathered over the sailboat regatta.",
    "The meditation room smelled faintly of eucalyptus and sea salt."
]

RED_SENTENCES = [
    "Campfire sparks danced upward and singed the night air.",
    "The bakery's ovens roared, bathing the loaves in hearthlight.",
    "A parade of lanterns wound through the festival streets.",
    "She wore a silk dress patterned with blooming poppies.",
    "Fresh pomegranates burst under the vendor's knife.",
    "Sunset spilled over the desert like molten glass.",
    "Chili peppers dried in long strings across the kitchen window.",
    "The forge hammered new horseshoes, glowing with heat.",
    "A fox darted through autumn bracken with a flash of tail.",
    "The vineyard's last grapes hung heavy in the evening blaze.",
    "Her manicure shimmered like polished coral.",
    "Saffron threads steeped in the simmering broth.",
    "Cherry blossoms carpeted the shrine path after the storm.",
    "A field of tulips swayed under the warm spring gust.",
    "The espresso machine hissed next to jars of paprika.",
    "He admired the vintage roadster with its lacquered finish.",
    "Comets streaked across the planetarium ceiling.",
    "The matador saluted beneath the rustling crowd.",
    "A violinist tuned strings that glowed in stage lights.",
    "Peaches bruised in the orchard crate after the long haul.",
    "Holiday ribbons fluttered from every lamppost downtown.",
    "The chef torched sugar atop the crème brûlée.",
    "A colony of fire ants marched along the garden stones.",
    "Meteor showers rained over the canyon lookout.",
    "Brick kilns smoked on the edge of the pottery village.",
    "The basketball bounced off the rim with a bright sheen.",
    "An heirloom cookbook smelled of cinnamon and clove.",
    "Glassblowers coaxed molten sand into swirling vases.",
    "Lanternfish flickered through the reef at dusk.",
    "A storm warning blared on the lighthouse radio.",
    "Embers drifted from the charcoal grill after the game.",
    "Cranberries bobbed in the harvest festival fountain.",
    "She painted her nails the shade of persimmon skins.",
    "The marching band uniforms sparkled beneath stadium lights.",
    "His tie carried a pattern of blooming camellias.",
    "The dragon fruit stand crowded the market entrance.",
    "Hikers gathered around a beacon atop the misty ridge.",
    "The pottery glaze resembled molten lava cooled midstream.",
    "A vintage theater sign flickered outside the gala.",
    "Fireworks erupted above the riverside promenade.",
    "Tomato vines twisted around the backyard trellis.",
    "A trail of rose petals led toward the proposal spot.",
    "Spiced cider steamed in enamel mugs at the cabin door.",
    "The racecar's taillights streaked across the track.",
    "She arranged a bouquet of gerberas in a sunlit studio.",
    "An artist layered oil paints like molten embers on canvas.",
    "A hawk's plumage flashed as it soared over the canyon.",
    "The brick courtyard radiated warmth long after sunset.",
    "Candlelight flickered against the velvet theater curtains.",
    "He sliced watermelon wedges for the picnic crowd."
]

ALL_TEST_SENTENCES = BLUE_SENTENCES + RED_SENTENCES
